package com.qinrenzaixian.dao.user;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.qinrenzaixian.domain.user.User;
import com.qinrenzaixian.domain.user.UserExample;
import java.sql.SQLException;
import java.util.List;

public class UserDAOImpl implements UserDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public UserDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int countByExample(UserExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int deleteByExample(UserExample example) throws SQLException {
        int rows = sqlMapClient.delete("user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        User key = new User();
        key.setId(id);
        int rows = sqlMapClient.delete("user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void insert(User record) throws SQLException {
        sqlMapClient.insert("user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void insertSelective(User record) throws SQLException {
        sqlMapClient.insert("user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public List selectByExample(UserExample example) throws SQLException {
        List list = sqlMapClient.queryForList("user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public User selectByPrimaryKey(Integer id) throws SQLException {
        User key = new User();
        key.setId(id);
        User record = (User) sqlMapClient.queryForObject("user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int updateByExampleSelective(User record, UserExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int updateByExample(User record, UserExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int updateByPrimaryKeySelective(User record) throws SQLException {
        int rows = sqlMapClient.update("user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public int updateByPrimaryKey(User record) throws SQLException {
        int rows = sqlMapClient.update("user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private static class UpdateByExampleParms extends UserExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}