package com.qinrenzaixian.domain.user;

import java.util.Date;

public class User {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.id
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.type
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Byte type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.name
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.sex
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Boolean sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.birthday
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String birthday;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.real_name
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String realName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.password
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.picture
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String picture;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.identity
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String identity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.identity_pic
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String identitypic;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.email
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.mobile
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.telephone
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.qq
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String qq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.weixin
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String weixin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.weibo
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String weibo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.address
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Integer address;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.login_times
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Integer loginTimes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.last_login_time
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Date lastLoginTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.last_login_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String lastLoginIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.create_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String createIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.createtime
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.creater
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Integer creater;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.update_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private String updateIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.updatetime
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.updater
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Integer updater;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.delflag
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Boolean delflag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.status
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    private Boolean status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.real_name
     *
     * @return the value of user.real_name
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.real_name
     *
     * @param realName the value for user.real_name
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.picture
     *
     * @return the value of user.picture
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.picture
     *
     * @param picture the value for user.picture
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.identity
     *
     * @return the value of user.identity
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.identity
     *
     * @param identity the value for user.identity
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.identity_pic
     *
     * @return the value of user.identity_pic
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getIdentitypic() {
        return identitypic;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.identity_pic
     *
     * @param identitypic the value for user.identity_pic
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setIdentitypic(String identitypic) {
        this.identitypic = identitypic;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.weixin
     *
     * @return the value of user.weixin
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.weixin
     *
     * @param weixin the value for user.weixin
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.weibo
     *
     * @return the value of user.weibo
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.weibo
     *
     * @param weibo the value for user.weibo
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setAddress(Integer address) {
        this.address = address;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.login_times
     *
     * @return the value of user.login_times
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.login_times
     *
     * @param loginTimes the value for user.login_times
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.last_login_time
     *
     * @return the value of user.last_login_time
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.last_login_time
     *
     * @param lastLoginTime the value for user.last_login_time
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.last_login_ip
     *
     * @return the value of user.last_login_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.last_login_ip
     *
     * @param lastLoginIp the value for user.last_login_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.create_ip
     *
     * @return the value of user.create_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.create_ip
     *
     * @param createIp the value for user.create_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setCreateIp(String createIp) {
        this.createIp = createIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.createtime
     *
     * @return the value of user.createtime
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.createtime
     *
     * @param createtime the value for user.createtime
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.creater
     *
     * @return the value of user.creater
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.creater
     *
     * @param creater the value for user.creater
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.update_ip
     *
     * @return the value of user.update_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public String getUpdateIp() {
        return updateIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.update_ip
     *
     * @param updateIp the value for user.update_ip
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setUpdateIp(String updateIp) {
        this.updateIp = updateIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.updatetime
     *
     * @return the value of user.updatetime
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.updatetime
     *
     * @param updatetime the value for user.updatetime
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.updater
     *
     * @return the value of user.updater
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.updater
     *
     * @param updater the value for user.updater
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.delflag
     *
     * @return the value of user.delflag
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.delflag
     *
     * @param delflag the value for user.delflag
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @ibatorgenerated Mon Jun 01 22:55:05 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}